service: s3-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  profile: serverless-admin
  stage: dev
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
        - "s3:*"
      Resource:
        - "*"

custom:
  bucket: s3-encora-task
  pythonRequirements:
      pythonBin: /usr/local/bin/python3.9

functions:
  jsontoxml:
    handler: jsontoxmlconverter.jsontoxml
    events:
      - http:
          path: generate/xml
          method: post
          cors: true

resources:
  Resources:
    JsontoXmlTask:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s3-encora-task

plugins:
  - serverless-python-requirements
